server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uber_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: uber-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.koji.uberdemo3.message,java.util,java.lang"
        spring.json.value.default.type: "com.koji.uberdemo3.message.LocationMessage"
        spring.json.use.type.headers: false
      enable-auto-commit: true
      auto-commit-interval: 1000
      max-poll-records: 500
      fetch-min-size: 1
      fetch-max-wait: 500

jwt:
  secret: your-secret-key-here-must-be-at-least-32-characters-long
  expiration: 86400000 # 24 hours in milliseconds

uber:
  pricing:
    base-fare: 2.50
    per-mile: 1.50
    per-minute: 0.30
  radius:
    driver-search: 5 # miles 